///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CreateComplaintRequestBody {
/*
{
  "identification_key": "azep0098",
  "trip_id": 1,
  "subject": "KM HIGH",
  "complaints": "mismatch in km"
}
*/

  String? identificationKey;
  int? tripId;
  String? subject;
  String? complaints;

  CreateComplaintRequestBody({
    this.identificationKey,
    this.tripId,
    this.subject,
    this.complaints,
  });
  CreateComplaintRequestBody.fromJson(Map<String, dynamic> json) {
    identificationKey = json['identification_key']?.toString();
    tripId = json['trip_id']?.toInt();
    subject = json['subject']?.toString();
    complaints = json['complaints']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['identification_key'] = identificationKey;
    data['trip_id'] = tripId;
    data['subject'] = subject;
    data['complaints'] = complaints;
    return data;
  }
}



///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CreateComplaintResponseResult {
/*
{
  "complaint_id": 6,
  "message": "Complaint Added Successfully"
}
*/

  int? complaintId;
  String? message;

  CreateComplaintResponseResult({
    this.complaintId,
    this.message,
  });
  CreateComplaintResponseResult.fromJson(Map<String, dynamic> json) {
    complaintId = json['complaint_id']?.toInt();
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['complaint_id'] = complaintId;
    data['message'] = message;
    return data;
  }
}

class CreateComplaintResponse {
/*
{
  "result": {
    "complaint_id": 6,
    "message": "Complaint Added Successfully"
  },
  "message": "Request Processed Succesfully",
  "status": "Success"
}
*/

  CreateComplaintResponseResult? result;
  String? message;
  String? status;

  CreateComplaintResponse({
    this.result,
    this.message,
    this.status,
  });
  CreateComplaintResponse.fromJson(Map<String, dynamic> json) {
    result = (json['result'] != null) ? CreateComplaintResponseResult.fromJson(json['result']) : null;
    message = json['message']?.toString();
    status = json['status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (result != null) {
      data['result'] = result!.toJson();
    }
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}

