///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetComplaintsResponseResult {
/*
{
  "id": 2,
  "identification_key": "azep0098",
  "trip_id": 100,
  "subject": "mismatch in km",
  "complaints": "KM LOW",
  "status": "Pending",
  "created_at": "2023-03-25 15:11:15",
  "deleted_at": "2023-03-25 15:11:15"
}
*/

  int? id;
  String? identificationKey;
  int? tripId;
  String? subject;
  String? complaints;
  String? status;
  String? createdAt;
  String? deletedAt;

  GetComplaintsResponseResult({
    this.id,
    this.identificationKey,
    this.tripId,
    this.subject,
    this.complaints,
    this.status,
    this.createdAt,
    this.deletedAt,
  });
  GetComplaintsResponseResult.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    identificationKey = json['identification_key']?.toString();
    tripId = json['trip_id']?.toInt();
    subject = json['subject']?.toString();
    complaints = json['complaints']?.toString();
    status = json['status']?.toString();
    createdAt = json['created_at']?.toString();
    deletedAt = json['deleted_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['identification_key'] = identificationKey;
    data['trip_id'] = tripId;
    data['subject'] = subject;
    data['complaints'] = complaints;
    data['status'] = status;
    data['created_at'] = createdAt;
    data['deleted_at'] = deletedAt;
    return data;
  }
}

class GetComplaintsResponse {
/*
{
  "result": [
    {
      "id": 2,
      "identification_key": "azep0098",
      "trip_id": 100,
      "subject": "mismatch in km",
      "complaints": "KM LOW",
      "status": "Pending",
      "created_at": "2023-03-25 15:11:15",
      "deleted_at": "2023-03-25 15:11:15"
    }
  ],
  "message": "Request Processed Succesfully",
  "status": "Success"
}
*/

  List<GetComplaintsResponseResult?>? result;
  String? message;
  String? status;

  GetComplaintsResponse({
    this.result,
    this.message,
    this.status,
  });
  GetComplaintsResponse.fromJson(Map<String, dynamic> json) {
    if (json['result'] != null) {
      final v = json['result'];
      final arr0 = <GetComplaintsResponseResult>[];
      v.forEach((v) {
        arr0.add(GetComplaintsResponseResult.fromJson(v));
      });
      result = arr0;
    }
    message = json['message']?.toString();
    status = json['status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (result != null) {
      final v = result;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['result'] = arr0;
    }
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}
