///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetFareResponseResultData {
/*
{
  "id": 1,
  "identification_key": "Default",
  "fare_name": "Fare-Standard",
  "fare_template_id": 1,
  "currency_id": 1,
  "fraction_digit": 2,
  "measure_unit": "KM",
  "base_fare": 40,
  "min_km": 1.7999999523162842,
  "cost_per_minute": 0.15000000596046448,
  "cost_per_unit": 18,
  "additional_fare": 20,
  "is_default": 0,
  "created_at": "2023-03-31 15:10:37",
  "updated_at": "2023-03-31 15:10:37"
}
*/

  int? id;
  String? identificationKey;
  String? fareName;
  int? fareTemplateId;
  int? currencyId;
  int? fractionDigit;
  String? measureUnit;
  int? baseFare;
  double? minKm;
  double? costPerMinute;
  int? costPerUnit;
  int? additionalFare;
  int? isDefault;
  String? createdAt;
  String? updatedAt;

  GetFareResponseResultData({
    this.id,
    this.identificationKey,
    this.fareName,
    this.fareTemplateId,
    this.currencyId,
    this.fractionDigit,
    this.measureUnit,
    this.baseFare,
    this.minKm,
    this.costPerMinute,
    this.costPerUnit,
    this.additionalFare,
    this.isDefault,
    this.createdAt,
    this.updatedAt,
  });
  GetFareResponseResultData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    identificationKey = json['identification_key']?.toString();
    fareName = json['fare_name']?.toString();
    fareTemplateId = json['fare_template_id']?.toInt();
    currencyId = json['currency_id']?.toInt();
    fractionDigit = json['fraction_digit']?.toInt();
    measureUnit = json['measure_unit']?.toString();
    baseFare = json['base_fare']?.toInt();
    minKm = json['min_km']?.toDouble();
    costPerMinute = json['cost_per_minute']?.toDouble();
    costPerUnit = json['cost_per_unit']?.toInt();
    additionalFare = json['additional_fare']?.toInt();
    isDefault = json['is_default']?.toInt();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['identification_key'] = identificationKey;
    data['fare_name'] = fareName;
    data['fare_template_id'] = fareTemplateId;
    data['currency_id'] = currencyId;
    data['fraction_digit'] = fractionDigit;
    data['measure_unit'] = measureUnit;
    data['base_fare'] = baseFare;
    data['min_km'] = minKm;
    data['cost_per_minute'] = costPerMinute;
    data['cost_per_unit'] = costPerUnit;
    data['additional_fare'] = additionalFare;
    data['is_default'] = isDefault;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}

class GetFareResponseResult {
/*
{
  "data": [
    {
      "id": 1,
      "identification_key": "Default",
      "fare_name": "Fare-Standard",
      "fare_template_id": 1,
      "currency_id": 1,
      "fraction_digit": 2,
      "measure_unit": "KM",
      "base_fare": 40,
      "min_km": 1.7999999523162842,
      "cost_per_minute": 0.15000000596046448,
      "cost_per_unit": 18,
      "additional_fare": 20,
      "is_default": 0,
      "created_at": "2023-03-31 15:10:37",
      "updated_at": "2023-03-31 15:10:37"
    }
  ],
  "Messsage": ""
}
*/

  List<GetFareResponseResultData?>? data;
  String? Messsage;

  GetFareResponseResult({
    this.data,
    this.Messsage,
  });
  GetFareResponseResult.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <GetFareResponseResultData>[];
      v.forEach((v) {
        arr0.add(GetFareResponseResultData.fromJson(v));
      });
      this.data = arr0;
    }
    Messsage = json['Messsage']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['Messsage'] = Messsage;
    return data;
  }
}

class GetFareResponse {
/*
{
  "result": {
    "data": [
      {
        "id": 1,
        "identification_key": "Default",
        "fare_name": "Fare-Standard",
        "fare_template_id": 1,
        "currency_id": 1,
        "fraction_digit": 2,
        "measure_unit": "KM",
        "base_fare": 40,
        "min_km": 1.7999999523162842,
        "cost_per_minute": 0.15000000596046448,
        "cost_per_unit": 18,
        "additional_fare": 20,
        "is_default": 0,
        "created_at": "2023-03-31 15:10:37",
        "updated_at": "2023-03-31 15:10:37"
      }
    ],
    "Messsage": ""
  },
  "message": "Request Processed Succesfully",
  "status": "Success"
}
*/

  GetFareResponseResult? result;
  String? message;
  String? status;

  GetFareResponse({
    this.result,
    this.message,
    this.status,
  });
  GetFareResponse.fromJson(Map<String, dynamic> json) {
    result = (json['result'] != null) ? GetFareResponseResult.fromJson(json['result']) : null;
    message = json['message']?.toString();
    status = json['status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (result != null) {
      data['result'] = result!.toJson();
    }
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}
