///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OtpRequestBody {
/*
{
  "country_code": "+91",
  "phone": 6374115583
}
*/

  String? countryCode;
  int? phone;

  OtpRequestBody({
    this.countryCode,
    this.phone,
  });
  OtpRequestBody.fromJson(Map<String, dynamic> json) {
    countryCode = json['country_code']?.toString();
    phone = json['phone']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country_code'] = countryCode;
    data['phone'] = phone;
    return data;
  }
}


///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ValidateOtpRequestBody {
/*
{
  "phone": 9078563412,
  "otp": 123456
}
*/

  int? phone;
  int? otp;

  ValidateOtpRequestBody({
    this.phone,
    this.otp,
  });
  ValidateOtpRequestBody.fromJson(Map<String, dynamic> json) {
    phone = json['phone']?.toInt();
    otp = json['otp']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['phone'] = phone;
    data['otp'] = otp;
    return data;
  }
}



///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ValidateOtpResponseResultData {
/*
{
  "int": 2,
  "identification_key": "azep7943",
  "magic_link": "Asxcfgbnj123esv",
  "phone": 9078563412,
  "otp": 123456
}
*/

  int? theInt;
  String? identificationKey;
  String? magicLink;
  int? phone;
  int? otp;

  ValidateOtpResponseResultData({
    this.theInt,
    this.identificationKey,
    this.magicLink,
    this.phone,
    this.otp,
  });
  ValidateOtpResponseResultData.fromJson(Map<String, dynamic> json) {
    theInt = json['int']?.toInt();
    identificationKey = json['identification_key']?.toString();
    magicLink = json['magic_link']?.toString();
    phone = json['phone']?.toInt();
    otp = json['otp']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['int'] = theInt;
    data['identification_key'] = identificationKey;
    data['magic_link'] = magicLink;
    data['phone'] = phone;
    data['otp'] = otp;
    return data;
  }
}

class ValidateOtpResponseResult {
/*
{
  "data": {
    "int": 2,
    "identification_key": "azep7943",
    "magic_link": "Asxcfgbnj123esv",
    "phone": 9078563412,
    "otp": 123456
  },
  "Messsage": "Login successfully"
}
*/

  ValidateOtpResponseResultData? data;
  String? Messsage;

  ValidateOtpResponseResult({
    this.data,
    this.Messsage,
  });
  ValidateOtpResponseResult.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null) ? ValidateOtpResponseResultData.fromJson(json['data']) : null;
    Messsage = json['Messsage']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['Messsage'] = Messsage;
    return data;
  }
}

class ValidateOtpResponse {
/*
{
  "result": {
    "data": {
      "int": 2,
      "identification_key": "azep7943",
      "magic_link": "Asxcfgbnj123esv",
      "phone": 9078563412,
      "otp": 123456
    },
    "Messsage": "Login successfully"
  },
  "message": "Request Processed Succesfully",
  "status": "Success"
}
*/

  ValidateOtpResponseResult? result;
  String? message;
  String? status;

  ValidateOtpResponse({
    this.result,
    this.message,
    this.status,
  });
  ValidateOtpResponse.fromJson(Map<String, dynamic> json) {
    result = (json['result'] != null) ? ValidateOtpResponseResult.fromJson(json['result']) : null;
    message = json['message']?.toString();
    status = json['status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (result != null) {
      data['result'] = result!.toJson();
    }
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}


