///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///

class TripHistoryResponseResult {
/*
{
  "trip_id": 5,
  "trip_date": "2023-03-31 17:29:11",
  "pickup_address": "",
  "drop_address": "",
  "status": "COMPLETED"
}
*/

  int? tripId;
  String? tripDate;
  String? pickupAddress;
  String? dropAddress;
  String? status;

  TripHistoryResponseResult({
    this.tripId,
    this.tripDate,
    this.pickupAddress,
    this.dropAddress,
    this.status,
  });
  TripHistoryResponseResult.fromJson(Map<String, dynamic> json) {
    tripId = json['trip_id']?.toInt();
    tripDate = json['trip_date']?.toString();
    pickupAddress = json['pickup_address']?.toString();
    dropAddress = json['drop_address']?.toString();
    status = json['status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['trip_id'] = tripId;
    data['trip_date'] = tripDate;
    data['pickup_address'] = pickupAddress;
    data['drop_address'] = dropAddress;
    data['status'] = status;
    return data;
  }
}

class TripHistoryResponse {
/*
{
  "result": [
    {
      "trip_id": 5,
      "trip_date": "2023-03-31 17:29:11",
      "pickup_address": "",
      "drop_address": "",
      "status": "COMPLETED"
    }
  ],
  "message": "Request Processed Succesfully",
  "status": "Success"
}
*/

  List<TripHistoryResponseResult?>? result;
  String? message;
  String? status;

  TripHistoryResponse({
    this.result,
    this.message,
    this.status,
  });
  TripHistoryResponse.fromJson(Map<String, dynamic> json) {
    if (json['result'] != null) {
      final v = json['result'];
      final arr0 = <TripHistoryResponseResult>[];
      v.forEach((v) {
        arr0.add(TripHistoryResponseResult.fromJson(v));
      });
      result = arr0;
    }
    message = json['message']?.toString();
    status = json['status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (result != null) {
      final v = result;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['result'] = arr0;
    }
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}
