///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UpdateFareRequestBodyFareInfo {
/*
{
  "fare_name": "Fare-Standard",
  "currency_id": 1,
  "fraction_digit": 2,
  "measure_unit": "KM",
  "base_fare": 50,
  "min_km": 1.8,
  "cost_per_minute": 0.15,
  "cost_per_unit": 18,
  "additional_fare": 20
}
*/

  String? fareName;
  int? currencyId;
  int? fractionDigit;
  String? measureUnit;
  int? baseFare;
  double? minKm;
  double? costPerMinute;
  int? costPerUnit;
  int? additionalFare;

  UpdateFareRequestBodyFareInfo({
    this.fareName,
    this.currencyId,
    this.fractionDigit,
    this.measureUnit,
    this.baseFare,
    this.minKm,
    this.costPerMinute,
    this.costPerUnit,
    this.additionalFare,
  });
  UpdateFareRequestBodyFareInfo.fromJson(Map<String, dynamic> json) {
    fareName = json['fare_name']?.toString();
    currencyId = json['currency_id']?.toInt();
    fractionDigit = json['fraction_digit']?.toInt();
    measureUnit = json['measure_unit']?.toString();
    baseFare = json['base_fare']?.toInt();
    minKm = json['min_km']?.toDouble();
    costPerMinute = json['cost_per_minute']?.toDouble();
    costPerUnit = json['cost_per_unit']?.toInt();
    additionalFare = json['additional_fare']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['fare_name'] = fareName;
    data['currency_id'] = currencyId;
    data['fraction_digit'] = fractionDigit;
    data['measure_unit'] = measureUnit;
    data['base_fare'] = baseFare;
    data['min_km'] = minKm;
    data['cost_per_minute'] = costPerMinute;
    data['cost_per_unit'] = costPerUnit;
    data['additional_fare'] = additionalFare;
    return data;
  }
}

class UpdateFareRequestBody {
/*
{
  "fare_id": 10,
  "driver_key": "azep0037",
  "fare_info": {
    "fare_name": "Fare-Standard",
    "currency_id": 1,
    "fraction_digit": 2,
    "measure_unit": "KM",
    "base_fare": 50,
    "min_km": 1.8,
    "cost_per_minute": 0.15,
    "cost_per_unit": 18,
    "additional_fare": 20
  }
}
*/

  int? fareId;
  String? driverKey;
  UpdateFareRequestBodyFareInfo? fareInfo;

  UpdateFareRequestBody({
    this.fareId,
    this.driverKey,
    this.fareInfo,
  });
  UpdateFareRequestBody.fromJson(Map<String, dynamic> json) {
    fareId = json['fare_id']?.toInt();
    driverKey = json['driver_key']?.toString();
    fareInfo = (json['fare_info'] != null) ? UpdateFareRequestBodyFareInfo.fromJson(json['fare_info']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['fare_id'] = fareId;
    data['driver_key'] = driverKey;
    if (fareInfo != null) {
      data['fare_info'] = fareInfo!.toJson();
    }
    return data;
  }
}
