
///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UpdateProfileRequestBody {
/*
{
  "identification_key": "azep8066",
  "driver_id": "1234",
  "name": "admin",
  "vehicle_number": "TN99H9900",
  "phone": 9078563412,
  "otp": 123456
}
*/

  String? identificationKey;
  String? driverId;
  String? name;
  String? vehicleNumber;
  int? phone;
  int? otp;

  UpdateProfileRequestBody({
    this.identificationKey,
    this.driverId,
    this.name,
    this.vehicleNumber,
    this.phone,
    this.otp,
  });
  UpdateProfileRequestBody.fromJson(Map<String, dynamic> json) {
    identificationKey = json['identification_key']?.toString();
    driverId = json['driver_id']?.toString();
    name = json['name']?.toString();
    vehicleNumber = json['vehicle_number']?.toString();
    phone = json['phone']?.toInt();
    otp = json['otp']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['identification_key'] = identificationKey;
    data['driver_id'] = driverId;
    data['name'] = name;
    data['vehicle_number'] = vehicleNumber;
    data['phone'] = phone;
    data['otp'] = otp;
    return data;
  }
}


class UpdateProfileResponseResult {
/*
{
  "Messsage": "Profile Updated Successfully"
}
*/

  String? Messsage;

  UpdateProfileResponseResult({
    this.Messsage,
  });
  UpdateProfileResponseResult.fromJson(Map<String, dynamic> json) {
    Messsage = json['Messsage']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Messsage'] = Messsage;
    return data;
  }
}

class UpdateProfileResponse {
/*
{
  "result": {
    "Messsage": "Profile Updated Successfully"
  },
  "message": "Request Processed Succesfully",
  "status": "Success"
}
*/

  UpdateProfileResponseResult? result;
  String? message;
  String? status;

  UpdateProfileResponse({
    this.result,
    this.message,
    this.status,
  });
  UpdateProfileResponse.fromJson(Map<String, dynamic> json) {
    result = (json['result'] != null) ? UpdateProfileResponseResult.fromJson(json['result']) : null;
    message = json['message']?.toString();
    status = json['status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (result != null) {
      data['result'] = result!.toJson();
    }
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}
