///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserProfileRequestBody {
/*
{
  "driver_id": "1234",
  "name": "admin",
  "vehicle_number": "TN99H9900",
  "phone": 9078563412,
  "otp": 123456
}
*/

  String? driverId;
  String? name;
  String? vehicleNumber;
  int? phone;
  int? otp;

  UserProfileRequestBody({
    this.driverId,
    this.name,
    this.vehicleNumber,
    this.phone,
    this.otp,
  });
  UserProfileRequestBody.fromJson(Map<String, dynamic> json) {
    driverId = json['driver_id']?.toString();
    name = json['name']?.toString();
    vehicleNumber = json['vehicle_number']?.toString();
    phone = json['phone']?.toInt();
    otp = json['otp']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['driver_id'] = driverId;
    data['name'] = name;
    data['vehicle_number'] = vehicleNumber;
    data['phone'] = phone;
    data['otp'] = otp;
    return data;
  }
}
