///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetUserResponseResultData {
/*
{
  "int": 21,
  "identification_key": "azep9879",
  "driver_id": "003",
  "name": "Anwar",
  "country_code": "+91",
  "magic_link": "_hFengo5bpZHQXjb1eIuJG8VPZ9qKu2XCPn6aKkb_pQ=",
  "vehicle_number": "TN99H9900",
  "phone": 6374115583,
  "otp": 5306,
  "status": "A",
  "created_at": "2023-04-06 08:26:58",
  "updated_at": "2023-04-06 13:56:58"
}
*/

  int? theInt;
  String? identificationKey;
  String? driverId;
  String? name;
  String? countryCode;
  String? magicLink;
  String? vehicleNumber;
  int? phone;
  int? otp;
  String? status;
  String? createdAt;
  String? updatedAt;

  GetUserResponseResultData({
    this.theInt,
    this.identificationKey,
    this.driverId,
    this.name,
    this.countryCode,
    this.magicLink,
    this.vehicleNumber,
    this.phone,
    this.otp,
    this.status,
    this.createdAt,
    this.updatedAt,
  });
  GetUserResponseResultData.fromJson(Map<String, dynamic> json) {
    theInt = json['int']?.toInt();
    identificationKey = json['identification_key']?.toString();
    driverId = json['driver_id']?.toString();
    name = json['name']?.toString();
    countryCode = json['country_code']?.toString();
    magicLink = json['magic_link']?.toString();
    vehicleNumber = json['vehicle_number']?.toString();
    phone = json['phone']?.toInt();
    otp = json['otp']?.toInt();
    status = json['status']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['int'] = theInt;
    data['identification_key'] = identificationKey;
    data['driver_id'] = driverId;
    data['name'] = name;
    data['country_code'] = countryCode;
    data['magic_link'] = magicLink;
    data['vehicle_number'] = vehicleNumber;
    data['phone'] = phone;
    data['otp'] = otp;
    data['status'] = status;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}

class GetUserResponseResult {
/*
{
  "data": {
    "int": 21,
    "identification_key": "azep9879",
    "driver_id": "003",
    "name": "Anwar",
    "country_code": "+91",
    "magic_link": "_hFengo5bpZHQXjb1eIuJG8VPZ9qKu2XCPn6aKkb_pQ=",
    "vehicle_number": "TN99H9900",
    "phone": 6374115583,
    "otp": 5306,
    "status": "A",
    "created_at": "2023-04-06 08:26:58",
    "updated_at": "2023-04-06 13:56:58"
  },
  "Messsage": ""
}
*/

  GetUserResponseResultData? data;
  String? Messsage;

  GetUserResponseResult({
    this.data,
    this.Messsage,
  });
  GetUserResponseResult.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null) ? GetUserResponseResultData.fromJson(json['data']) : null;
    Messsage = json['Messsage']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['Messsage'] = Messsage;
    return data;
  }
}

class GetUserResponse {
/*
{
  "result": {
    "data": {
      "int": 21,
      "identification_key": "azep9879",
      "driver_id": "003",
      "name": "Anwar",
      "country_code": "+91",
      "magic_link": "_hFengo5bpZHQXjb1eIuJG8VPZ9qKu2XCPn6aKkb_pQ=",
      "vehicle_number": "TN99H9900",
      "phone": 6374115583,
      "otp": 5306,
      "status": "A",
      "created_at": "2023-04-06 08:26:58",
      "updated_at": "2023-04-06 13:56:58"
    },
    "Messsage": ""
  },
  "message": "Request Processed Succesfully",
  "status": "Success"
}
*/

  GetUserResponseResult? result;
  String? message;
  String? status;

  GetUserResponse({
    this.result,
    this.message,
    this.status,
  });
  GetUserResponse.fromJson(Map<String, dynamic> json) {
    result = (json['result'] != null) ? GetUserResponseResult.fromJson(json['result']) : null;
    message = json['message']?.toString();
    status = json['status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (result != null) {
      data['result'] = result!.toJson();
    }
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}
