///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UpdateProfileResponseResult {
/*
{
  "Messsage": "Profile Updated Successfully"
} 
*/

  String? Messsage;

  UpdateProfileResponseResult({
    this.Messsage,
  });
  UpdateProfileResponseResult.fromJson(Map<String, dynamic> json) {
    Messsage = json['Messsage']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Messsage'] = Messsage;
    return data;
  }
}

class UpdateProfileResponse {
/*
{
  "result": {
    "Messsage": "Profile Updated Successfully"
  },
  "message": "Request Processed Succesfully",
  "status": "Success"
} 
*/

  UpdateProfileResponseResult? result;
  String? message;
  String? status;

  UpdateProfileResponse({
    this.result,
    this.message,
    this.status,
  });
  UpdateProfileResponse.fromJson(Map<String, dynamic> json) {
    result = (json['result'] != null) ? UpdateProfileResponseResult.fromJson(json['result']) : null;
    message = json['message']?.toString();
    status = json['status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (result != null) {
      data['result'] = result!.toJson();
    }
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}
