///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UpdateProfileRequestBody {
/*
{
  "driver_id": "003",
  "name": "Anwar",
  "vehicle_number": "TN99H9900"
}
*/

  String? driverId;
  String? name;
  String? vehicleNumber;

  UpdateProfileRequestBody({
    this.driverId,
    this.name,
    this.vehicleNumber,
  });
  UpdateProfileRequestBody.fromJson(Map<String, dynamic> json) {
    driverId = json['driver_id']?.toString();
    name = json['name']?.toString();
    vehicleNumber = json['vehicle_number']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['driver_id'] = driverId;
    data['name'] = name;
    data['vehicle_number'] = vehicleNumber;
    return data;
  }
}
