///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TripCompleteResponseResultFare {
/*
{
  "total_fare": "60.01",
  "base_fare": "40",
  "distance_fare": "40",
  "waiting_fare": "0.01",
  "surge_price": "1",
  "additional_fare": "20"
}
*/

  String? totalFare;
  String? baseFare;
  String? distanceFare;
  String? waitingFare;
  String? surgePrice;
  String? additionalFare;

  TripCompleteResponseResultFare({
    this.totalFare,
    this.baseFare,
    this.distanceFare,
    this.waitingFare,
    this.surgePrice,
    this.additionalFare,
  });
  TripCompleteResponseResultFare.fromJson(Map<String, dynamic> json) {
    totalFare = json['total_fare']?.toString();
    baseFare = json['base_fare']?.toString();
    distanceFare = json['distance_fare']?.toString();
    waitingFare = json['waiting_fare']?.toString();
    surgePrice = json['surge_price']?.toString();
    additionalFare = json['additional_fare']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['total_fare'] = totalFare;
    data['base_fare'] = baseFare;
    data['distance_fare'] = distanceFare;
    data['waiting_fare'] = waitingFare;
    data['surge_price'] = surgePrice;
    data['additional_fare'] = additionalFare;
    return data;
  }
}

class TripCompleteResponseResultReading {
/*
{
  "km_travelled": "8.19",
  "waiting_time": "300"
}
*/

  String? kmTravelled;
  String? waitingTime;

  TripCompleteResponseResultReading({
    this.kmTravelled,
    this.waitingTime,
  });
  TripCompleteResponseResultReading.fromJson(Map<String, dynamic> json) {
    kmTravelled = json['km_travelled']?.toString();
    waitingTime = json['waiting_time']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['km_travelled'] = kmTravelled;
    data['waiting_time'] = waitingTime;
    return data;
  }
}

class TripCompleteResponseResultTripDuration {
/*
{
  "duration": "300"
}
*/

  String? duration;

  TripCompleteResponseResultTripDuration({
    this.duration,
  });
  TripCompleteResponseResultTripDuration.fromJson(Map<String, dynamic> json) {
    duration = json['duration']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['duration'] = duration;
    return data;
  }
}

class TripCompleteResponseResult {
/*
{
  "trip_id": 41,
  "start_time": "2023-03-29 17:01:01",
  "end_time": "2023-03-29 20:00:20",
  "trip_duration": {
    "duration": "300"
  },
  "reading": {
    "km_travelled": "8.19",
    "waiting_time": "300"
  },
  "fare": {
    "total_fare": "60.01",
    "base_fare": "40",
    "distance_fare": "40",
    "waiting_fare": "0.01",
    "surge_price": "1",
    "additional_fare": "20"
  }
}
*/

  int? tripId;
  String? startTime;
  String? endTime;
  TripCompleteResponseResultTripDuration? tripDuration;
  TripCompleteResponseResultReading? reading;
  TripCompleteResponseResultFare? fare;

  TripCompleteResponseResult({
    this.tripId,
    this.startTime,
    this.endTime,
    this.tripDuration,
    this.reading,
    this.fare,
  });
  TripCompleteResponseResult.fromJson(Map<String, dynamic> json) {
    tripId = json['trip_id']?.toInt();
    startTime = json['start_time']?.toString();
    endTime = json['end_time']?.toString();
    tripDuration = (json['trip_duration'] != null) ? TripCompleteResponseResultTripDuration.fromJson(json['trip_duration']) : null;
    reading = (json['reading'] != null) ? TripCompleteResponseResultReading.fromJson(json['reading']) : null;
    fare = (json['fare'] != null) ? TripCompleteResponseResultFare.fromJson(json['fare']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['trip_id'] = tripId;
    data['start_time'] = startTime;
    data['end_time'] = endTime;
    if (tripDuration != null) {
      data['trip_duration'] = tripDuration!.toJson();
    }
    if (reading != null) {
      data['reading'] = reading!.toJson();
    }
    if (fare != null) {
      data['fare'] = fare!.toJson();
    }
    return data;
  }
}

class TripCompleteResponse {
/*
{
  "result": {
    "trip_id": 41,
    "start_time": "2023-03-29 17:01:01",
    "end_time": "2023-03-29 20:00:20",
    "trip_duration": {
      "duration": "300"
    },
    "reading": {
      "km_travelled": "8.19",
      "waiting_time": "300"
    },
    "fare": {
      "total_fare": "60.01",
      "base_fare": "40",
      "distance_fare": "40",
      "waiting_fare": "0.01",
      "surge_price": "1",
      "additional_fare": "20"
    }
  },
  "message": "Request Processed Succesfully",
  "status": "Success"
}
*/

  TripCompleteResponseResult? result;
  String? message;
  String? status;

  TripCompleteResponse({
    this.result,
    this.message,
    this.status,
  });
  TripCompleteResponse.fromJson(Map<String, dynamic> json) {
    result = (json['result'] != null) ? TripCompleteResponseResult.fromJson(json['result']) : null;
    message = json['message']?.toString();
    status = json['status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (result != null) {
      data['result'] = result!.toJson();
    }
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}
