///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TripHistoryResponseResult {
/*
{
  "trip_id": 4,
  "trip_date": "2023-03-31 14:33:14",
  "start_time": "2023-03-29 17:01:01",
  "end_time": "2023-03-29 20:00:20",
  "duration": "300",
  "distances": 0.008190000429749489,
  "total_fare": 60.0099983215332,
  "status": "COMPLETED"
}
*/

  int? tripId;
  String? tripDate;
  String? startTime;
  String? endTime;
  String? duration;
  double? distances;
  double? totalFare;
  String? status;

  TripHistoryResponseResult({
    this.tripId,
    this.tripDate,
    this.startTime,
    this.endTime,
    this.duration,
    this.distances,
    this.totalFare,
    this.status,
  });
  TripHistoryResponseResult.fromJson(Map<String, dynamic> json) {
    tripId = json['trip_id']?.toInt();
    tripDate = json['trip_date']?.toString();
    startTime = json['start_time']?.toString();
    endTime = json['end_time']?.toString();
    duration = json['duration']?.toString();
    distances = json['distances']?.toDouble();
    totalFare = json['total_fare']?.toDouble();
    status = json['status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['trip_id'] = tripId;
    data['trip_date'] = tripDate;
    data['start_time'] = startTime;
    data['end_time'] = endTime;
    data['duration'] = duration;
    data['distances'] = distances;
    data['total_fare'] = totalFare;
    data['status'] = status;
    return data;
  }
}

class TripHistoryResponse {
/*
{
  "result": [
    {
      "trip_id": 4,
      "trip_date": "2023-03-31 14:33:14",
      "start_time": "2023-03-29 17:01:01",
      "end_time": "2023-03-29 20:00:20",
      "duration": "300",
      "distances": 0.008190000429749489,
      "total_fare": 60.0099983215332,
      "status": "COMPLETED"
    }
  ],
  "message": "Request Processed Succesfully",
  "status": "Success"
}
*/

  List<TripHistoryResponseResult?>? result;
  String? message;
  String? status;

  TripHistoryResponse({
    this.result,
    this.message,
    this.status,
  });
  TripHistoryResponse.fromJson(Map<String, dynamic> json) {
    if (json['result'] != null) {
      final v = json['result'];
      final arr0 = <TripHistoryResponseResult>[];
      v.forEach((v) {
        arr0.add(TripHistoryResponseResult.fromJson(v));
      });
      result = arr0;
    }
    message = json['message']?.toString();
    status = json['status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (result != null) {
      final v = result;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['result'] = arr0;
    }
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}
