///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TripCompleteRequestBodyReadings {
/*
{
  "km_travelled": 9.19,
  "waiting_time": 300,
  "surge_value": 1.5
}
*/

  double? kmTravelled;
  int? waitingTime;
  double? surgeValue;

  TripCompleteRequestBodyReadings({
    this.kmTravelled,
    this.waitingTime,
    this.surgeValue,
  });
  TripCompleteRequestBodyReadings.fromJson(Map<String, dynamic> json) {
    kmTravelled = json['km_travelled']?.toDouble();
    waitingTime = json['waiting_time']?.toInt();
    surgeValue = json['surge_value']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['km_travelled'] = kmTravelled;
    data['waiting_time'] = waitingTime;
    data['surge_value'] = surgeValue;
    return data;
  }
}

class TripCompleteRequestBodyDestination {
/*
{
  "latitude": "10.978840",
  "longitude": "76.961304"
}
*/

  String? latitude;
  String? longitude;

  TripCompleteRequestBodyDestination({
    this.latitude,
    this.longitude,
  });
  TripCompleteRequestBodyDestination.fromJson(Map<String, dynamic> json) {
    latitude = json['latitude']?.toString();
    longitude = json['longitude']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['latitude'] = latitude;
    data['longitude'] = longitude;
    return data;
  }
}

class TripCompleteRequestBodyOrigin {
/*
{
  "latitude": "10.970125",
  "longitude": "76.951640"
}
*/

  String? latitude;
  String? longitude;

  TripCompleteRequestBodyOrigin({
    this.latitude,
    this.longitude,
  });
  TripCompleteRequestBodyOrigin.fromJson(Map<String, dynamic> json) {
    latitude = json['latitude']?.toString();
    longitude = json['longitude']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['latitude'] = latitude;
    data['longitude'] = longitude;
    return data;
  }
}

class TripCompleteRequestBody {
/*
{
  "identification_key": "azep0001",
  "fare_id": 1,
  "start_time": "2023-03-29 17:01:01",
  "end_time": "2023-03-29 20:00:20",
  "origin": {
    "latitude": "10.970125",
    "longitude": "76.951640"
  },
  "destination": {
    "latitude": "10.978840",
    "longitude": "76.961304"
  },
  "readings": {
    "km_travelled": 9.19,
    "waiting_time": 300,
    "surge_value": 1.5
  }
}
*/

  String? identificationKey;
  int? fareId;
  String? startTime;
  String? endTime;
  TripCompleteRequestBodyOrigin? origin;
  TripCompleteRequestBodyDestination? destination;
  TripCompleteRequestBodyReadings? readings;

  TripCompleteRequestBody({
    this.identificationKey,
    this.fareId,
    this.startTime,
    this.endTime,
    this.origin,
    this.destination,
    this.readings,
  });
  TripCompleteRequestBody.fromJson(Map<String, dynamic> json) {
    identificationKey = json['identification_key']?.toString();
    fareId = json['fare_id']?.toInt();
    startTime = json['start_time']?.toString();
    endTime = json['end_time']?.toString();
    origin = (json['origin'] != null) ? TripCompleteRequestBodyOrigin.fromJson(json['origin']) : null;
    destination = (json['destination'] != null) ? TripCompleteRequestBodyDestination.fromJson(json['destination']) : null;
    readings = (json['readings'] != null) ? TripCompleteRequestBodyReadings.fromJson(json['readings']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['identification_key'] = identificationKey;
    data['fare_id'] = fareId;
    data['start_time'] = startTime;
    data['end_time'] = endTime;
    if (origin != null) {
      data['origin'] = origin!.toJson();
    }
    if (destination != null) {
      data['destination'] = destination!.toJson();
    }
    if (readings != null) {
      data['readings'] = readings!.toJson();
    }
    return data;
  }
}





