///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CreateComplaintRequestBody {
/*
{
  "identification_key": "azep0098",
  "trip_id": 1,
  "subject": "KM HIGH",
  "complaints": "mismatch in km"
}
*/

  String? identificationKey;
  int? tripId;
  String? subject;
  String? complaints;

  CreateComplaintRequestBody({
    this.identificationKey,
    this.tripId,
    this.subject,
    this.complaints,
  });
  CreateComplaintRequestBody.fromJson(Map<String, dynamic> json) {
    identificationKey = json['identification_key']?.toString();
    tripId = json['trip_id']?.toInt();
    subject = json['subject']?.toString();
    complaints = json['complaints']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['identification_key'] = identificationKey;
    data['trip_id'] = tripId;
    data['subject'] = subject;
    data['complaints'] = complaints;
    return data;
  }
}


